version: '3.1'

services:
  app:
    build:
      context: ./docker
<<<<<<< HEAD
      dockerfile: apache.dockerfile
    image: imbityrk/learndocker2:latest
    ports:
      - 8000:80
    #volumes:
    # - ./html:/usr/local/apache2/htdocs
=======
      dockerfile: app.dockerfile
    ports:
      - 8000:80

  # apache:
  #   # image: httpd:2.4
  #   build:
  #     context: ./docker
  #     dockerfile: apache.dockerfile
  #   image: kasparsu/kit22learndocker:latest
  #   ports:
  #     - 8000:80
    # volumes:
    #   - ./html:/usr/local/apache2/htdocs

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
>>>>>>> fba3c6899634d1b643b153d2f1e89e6b6575786c

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  dbdata: